export enum ERegisterFormSteps {
  USER_FORM = 'USER_FORM',
  ORGANIZATION_FORM = 'ORGANIZATION_FORM',
  CONTACT_FORM = 'CONTACT_FORM',
  SERIES_SUCURSAL_FORM = 'SERIES_SUCURSAL_FORM',
  PLAN_FORM = 'PLAN_FORM',
}